### PR TITLE
bump version number so this runs on FF8.x

### PR DESCRIPTION
**Pull request by jensimmons**
I haven't tested Firepicker with FireFox 8, but I am bumping up the max version number from 8.0 to 8.9 so that it can be installed. 

I love Firepicker, and can't get my work done without it! :D

### CODE REVIEW

**Comment by jakecaputo** [comment]
@jensimmons How do I actually install this? I've been ripping my hair out. I uninstalled firepicker from my MacBook Pro and so I don't have any files to change, and the official add on won't let me "install anyway" (although, my iMac did).

**Comment by jensimmons** [comment]
Yeah, I couldn't figure out how to install this code either. I'm now assuming this code is used to make a Firefox Addon, and thedarkone needs to compile it and upload it to Mozilla.

I uninstalled Firepicker as well, so I couldn't modify the files. So instead I downgraded to FF7 and got back to work. Hopefully thedarkone will show up soon so we can all upgrade to FF8.

**Comment by ARS81** [comment]
I also can't live without this extension, so after I found this commit, I was successfully able to install it for Firefox8 doing these few little steps:

1) download the source (i used git clone)
2) edit the install.rdf: em:maxVersion value to 8.9 (thanks jensimmons!) and save it
3) compress all contents of this directory with zip to firepicker.zip
4) rename firepicker.zip to firepicker.xpi
5) open the extension manager of Firefox
6) if exists, uninstall previous (disabled) version of firepicker from Firefox
7) click on the little gear icon on the top-right and choose install extension from file
8) browse to your firepicker.xpi, select and install it

**Comment by jakecaputo** [comment]
@szegheo

Awesome, that worked for me.

Anybody else who tries this, note you CANNOT ZIP the folder with all the files and name it firepicker.xpi, you have to zip the CONTENTS of the folder. Otherwise you will get a 'corrupt file' error.

**Comment by thedarkone** [comment]
Hey @jensimmons, I've bumped the version to 9.\* for the current release of the plugin.

**Pull request closed without merging**
